## markdown
markdown:
  preset: 'default'
  render:
    html: true
    xhtmlOut: false
    langPrefix: 'language-'
    breaks: true
    linkify: true
    typographer: true
    quotes: '“”‘’'
  enable_rules:
  disable_rules:
  plugins:
  anchors:
    level: 2
    collisionSuffix: ''
    permalink: false
    permalinkClass: 'header-anchor'
    permalinkSide: 'left'
    permalinkSymbol: '¶'
    case: 0
    separator: '-'
  images:
    lazyload: false
    prepend_root: false
    post_asset: false
  inline: false  # https://markdown-it.github.io/markdown-it/#MarkdownIt.renderInline

plugins:
  - hexo-renderer-markdown-it 

# Social links configuration
social:
  - name: github
    url: 'https://github.com/18072150332/hexo-silk'
    icon: 'fa-github'
  - name: envelope
    url: 'mailto:18072150332@fudan.edu.cn'
    icon: 'fa-envelope'
  - name: weixin
    url: '#'
    icon: 'fa-weixin'
    qrcode: '/images/wechat-qrcode.png'

# 菜单
menus:
  - name: 首页
    url: '/'
  - name: 分类
    url: '#categories'
  - name: 标签
    url: '#tags'
  - name: 关于
    url: '#about'