## markdown
markdown:
  preset: 'default'
  render:
    html: true
    xhtmlOut: false
    langPrefix: 'language-'
    breaks: true
    linkify: true
    typographer: true
    quotes: '“”‘’'
  enable_rules:
  disable_rules:
  plugins:
  anchors:
    level: 2
    collisionSuffix: ''
    permalink: false
    permalinkClass: 'header-anchor'
    permalinkSide: 'left'
    permalinkSymbol: '¶'
    case: 0
    separator: '-'
  images:
    lazyload: false
    prepend_root: false
    post_asset: false
  inline: false  # https://markdown-it.github.io/markdown-it/#MarkdownIt.renderInline

plugins:
  - hexo-renderer-markdown-it 

# Social links configuration
social:
  - name: github
    url: '#'
    icon: 'fa-github'
  - name: envelope
    url: '#'
    icon: 'fa-envelope'
  - name: weixin
    url: '#'
    icon: 'fa-weixin'
    qrcode: '/images/wechat-qrcode.png'

# 作者信息配置
author:
  name: 独酌 # 页面展示作者名字
  avatar: /images/default-avatar.jpg ## 作者头像，放在主题source/images里
  bio: 小镇码农  ## 作者介绍